swagger: '2.0'
info:
  description: This is generic media service
  version: '1.0'
  title: Media Service
  termsOfService: www.test.com
  contact:
    name: PIK Team
    email: pikmserives@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: localhost
basePath: /media/v1.0
schemes:
  - http
paths:
  '/**/{folder:.*}':
    post:
      tags:
        - file-service-api
      summary: Upload a file.
      description: Upload a file and save it in the given path.
      operationId: uploadFile
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: 'folder:.*'
          in: path
          description: folder path where the file will be saved
          required: true
          type: string
        - name: file
          in: formData
          description: file to upload
          required: true
          type: file
      responses:
        '201':
          description: File created
          headers:
            Location:
              type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  '/**/{file:.*}.{ext}':
    get:
      tags:
        - file-service-api
      summary: Get a file.
      description: Get a single file given the full URL path and filename with extension.
      operationId: getFile
      parameters:
        - name: 'file:.*'
          in: path
          description: full path where the file will be retrieved
          required: true
          type: string
        - name: ext
          in: path
          description: extension of the file
          required: true
          type: string
        - name: scaleSize
          in: query
          description: scale to render image
          required: false
          type: integer
          format: int32
      responses:
        '200':
          description: File download successful.
          schema:
            type: file
        '204':
          description: No content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    delete:
      tags:
        - file-service-api
      summary: Delete a file.
      description: Update a file in the given path.
      operationId: deleteFile
      parameters:
        - name: 'file:.*'
          in: path
          description: full path where the file will be retrieved
          required: true
          type: string
        - name: ext
          in: path
          description: extension of the file
          required: true
          type: string
      responses:
        '204':
          description: File deleted
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Resource to delete not found
securityDefinitions:
  damagestore_auth:
    type: oauth2
    flow: accessCode
    authorizationUrl: 'https://localhost/sso/oauth2/authorize'
    tokenUrl: 'https://localhost/sso/oauth2/token'
    scopes:
      read: Grants read access
      write: Grants write access
